### ISSUE TITLE
Fix nav header

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#15]
Add the nav bar from the main website to the forums page.

**Comment by dags-** [comment]
NB - the [sponge forums](https://forums.spongepowered.org) ended up having to go with a drop-down list menu as a traditional left-to-right navbar clashed with discourse's existing functionality/mobile-friendliness

**Comment by Freshmilkymilk** [comment]
Looks like we have a good solution now. Just need to fix links when the full website goes up.
