### ISSUE TITLE
Modpack Page

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#16]
Make a guide on how to install the launcher. Also make a video for it. Add a guide on how to self install, with more emphasis on using the launcher.

**Comment by Freshmilkymilk** [comment]
Still gotta fiddle with a few things, but this is pretty much done. https://ardacraft.io/modpack/

**Comment by dags-** [comment]
Few wording tweaks (see commits), and added a blurb-y bit at the top:

repo:
https://github.com/dags-/ardacraft.github.io/tree/gh-pages

preview:
https://dags-.github.io/ardacraft.github.io/ardacraft/modpack/

**Comment by Freshmilkymilk** [comment]
Want to put a pull request to add this?
