### ISSUE TITLE
Site Optimizations

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#20]
Google has released a pretty neat tool for testing performance of, and suggesting optimizations for, websites:
https://testmysite.thinkwithgoogle.com/intl/en-gb

It could be an aim, as things progress towards the 'New Website' milestone, to improve the overall scores given by this tool.

**Comment by dags-** [comment]
Fixing issue #19 will probably show a decent bump for the mobile and desktop scores.
Could also look at utilizing Cloudflare optimizations more, if not already

**Comment by HenrySlawniak** [comment]
Done all I can server side to make ardacraft.io fly. Some client side tweaks could help as well.
