### ISSUE TITLE
Animation Plugin

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#23]
Allow for animation of a set of blocks such as doors, boats, etc.

**Comment by dags-** [comment]
# Thoughts:

Components:
- Animation triggers - a listener for event(s) that cause the animation to play
- Animation frames - the stop-motion frames that are pasted into the world at set intervals to create the top-motion style animation

Requirements:
- File storage format for animation frames
- File storage format for triggers
- Animation types
- Interactable triggers
- Smart loading, caching and unloading of triggers and frames


### Frame storage format
Sponge will have a [schematic format](https://github.com/SpongePowered/Schematic-Specification) built in. Not sure if this is targetting api 4.x (1.8.9) or if it'll be in later versions

### Trigger storage format
Something light-weight - json would probably be fine.  
Would contain:
- Location
- Activation range (how close to the Location users must be before the listeners start listening to trigger events)
- List of Listeners (support AND/OR behavior?)
- List of animations that should play
- ?

### Animation types
Support different types of animation:
- Basic - play a queue of frames in order (doors etc)
- Point-to-point - a single frame that travels between two points (boats, portcullis, etc)
- ?

Should support looping and playing in reverse

### Triggers
- Listen to user clicks on blocks/areas
- Listen to user chat for keywords
- ?

Triggers should be location specific, and would be linked to one or more animations.  
When a user is within x range of a trigger, the animation should be loaded from disk and stored in memory until no users are within range.  

Need to also consider how a trigger behaves when fired during an actively playing animation - ie is it ignored, does it stop the animation, does it reset the animation etc

### Caching
Would be a waist of memory to keep all animations loaded all the time. Should consider loading, caching, and then removing animations as needed - don't want to overly rely on io though

**Comment by Freshmilkymilk** [comment]
This has been completed:

[https://github.com/dags-/StopMotion](https://github.com/dags-/StopMotion)
[https://github.com/ArdaCraft/DoorsOfDurin](https://github.com/ArdaCraft/DoorsOfDurin)
