### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#30]
Have Dynmap embedded into another page. Like [WesterosCraft has for example](http://westeroscraft.com/map).

**Comment by Freshmilkymilk** [comment]
@HenrySlawniak got the map to work [here](https://ardacraft.io/map/). It might be a good idea to add the website header and footer to the page.

**Comment by HenrySlawniak** [comment]
That's just a proxy to provide SSL. Should just embed it on another page.
