### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#32]
Gotta fix/tweak a few things for Dynmap.
- [x] Zoom out more
- [ ] Add more angles to the surface view
- [x] Fix some of the textures that don't match to in-game

**Comment by dags-** [comment]
Services plugin also adds dynmap integrations for things like warp markers and regions:
https://github.com/dags-/Services

**Comment by dags-** [comment]
As CreativeBlock generates it's own dynmap model files, I'm able to fix some of the texture issues - double-height plants/crops for example.
