### ISSUE TITLE
Modblock torches missing

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#34]
Noticed some of the modblock torch/lanterns were missing - may be an issue with the world converter

**Comment by Freshmilkymilk** [comment]
Could be due to not having a no-physics plugin. Will have to test with the latest plugins/world converter.

**Comment by dags-** [comment]
The modblock torches already ignore physics updates, it's written into the mod. Pretty sure this is something else

**Comment by dags-** [comment]
Ok. Found the issue - the 1.7.10 mod registers torches with the wrong name format, currently:
`ACBlocks:Hanging_Lantern_Torch.name_1`

Where really, it should be:
`ACBlocks:Hanging_Lantern_Torch_1.name`

The world converter is expecting the latter, and so misses the former entirely - those blocks effectively get removed, which is why they've disappeared.

I'll have to add an extra couple of rules to the world converter to catch these cases.

**Comment by dags-** [comment]
**edit** found the actual issue - meta data value zero (`0`) wasn't being interpreted as a valid blockstate by the 1.8.9 mod.
Easy enough to fix
