### ISSUE TITLE
Cauldron to Sponge Migration

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#36]
## Server:
- [x] Ensure all mods/plugins are correct versions
- [x] Re-implement core functionality
 - [x] Protection against guest users
 - [x] Block vanilla mechanics like block decay/growth
 - [x] Building tools, like no physics ([toolkit](https://github.com/ArdaCraft/Toolkit))
 - [x] Warps
 - [x] Essential commands ([Bedrock](https://github.com/ArdaCraft/Bedrock))
 - [x] Dynmap
- [x] Add latest ACPaintings
- [x] Add NoClip
- [x] Set up chat formatting and badges
- [x] Set up permissions and ranks
- [x] Carry over users and assign to correct ranks

## World:
- [x] Convert world
 - [x] Postpone further work on 1.7.10 world
 - [x] Back-shit-up
 - [x] Run ACWorldFixer on world
 - [x] Probably best to reset player data
 - [x] Remove any crap left over from bibliocraft
 - [x] Transfer to server

## Services:
- [x] Update modpack
- [x] Update launcher
- [x] Update modpack installer
- [x] Resourcepack -> github release system
- [x] Download links and info pages to point to correct versions etc

**Comment by Atlantispy** [comment]
Just updated the [https://docs.google.com/spreadsheets/d/1EzMyHNCRR55ZUHdrz_SPZttuZFhWXpgVbMgJj-6MYaw/edit#gid=0](url)ranks sheet, can ensure that people have the correct ranks when we transfer over.

**Comment by dags-** [comment]
Thanks, will probably just make a quick script to convert the user data - saves someone having to plug in the command each time

**Comment by Atlantispy** [comment]
Anything I can do to help us update faster?
