### ISSUE TITLE
Add Plugins to Forums

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#39]
There are a lot of neat plugins that would be good to add to the forums.

Some examples:

1. https://github.com/lukegb/discourse-bbcode-spoiler
2. https://github.com/discourse/discourse-solved
3. https://github.com/ligthyear/discourse-plugin-shared-edit
4. https://github.com/rux-pizza/discourse-awesome-bbcodes
5. https://github.com/cpradio/discourse-plugin-composer-help-button
6. https://github.com/angusmcleod/discourse-quick-messages
7. https://github.com/discourse/discourse-spoiler-alert
8. https://github.com/discourse/discourse-cakeday
9. https://github.com/discourse/discourse-hide-post
10. https://github.com/discourse/github_badges
11. https://github.com/discourse/discourse-staff-notes
12. https://github.com/werweisswas/discourse-plugin-tagger
13. https://github.com/discourse/discourse-tagging

**Comment by dags-** [comment]
Ones I'm most interested in:
- One of the 'spoilers' plugins would be great
- The 'solved' plugin would be handy, particularly for the support forums
- Discourse already has tags, but if one of the plugins enriches them in some way, that might cool too

**Comment by Freshmilkymilk** [comment]
Added these plugins:
https://github.com/discourse/discourse-cakeday
https://github.com/discourse/discourse-spoiler-alert
https://github.com/discourse/discourse-solved

We may add more later, but for now this is sufficient.
