### ISSUE TITLE
VoxelSniper

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#40]
Current version of [VoxelSniper 7.1.0-SNAPSHOT](https://github.com/TVPT/VoxelSniper) is made for SpongeAPI-3.1.0, and is not compatible with our server target version (SpongeAPI-4.1.0).

[VoxelSniper 8.0.0-SNAPSHOT](https://github.com/TVPT/VoxelSniper/tree/version-8) targets SpongeAPI-5.0.0 so will also (probably) not be compatible.

Bum.

**Comment by Freshmilkymilk** [comment]
Looks like VoxelSniper is finally getting updated for [Sponge 1.10.2](https://github.com/TVPT/VoxelSniper/tree/sponge-1.10.2)

**Comment by dags-** [comment]
Custom build here:
https://ci.ardacraft.io/job/VoxelSniper/

Adds support for masking so that it can be used on plots
Fixes an error when interacting with blocks without an item in hand
