### ISSUE TITLE
1.8.9 Server Fixes

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#42]
A list of all things that need to be fixed or added to the 1.8.9 server.
- [x] Better Foliage is super buggy, will have to remove from modpack until some things are fixed

- [x] Need a solution to some old no-physics things we used to have. Things like having water not receive block updates

- [x] Worldedit seems to be a bit borked according to some people, not placing stairs and other objects in the right direction, and not working with modblocks (will have to test to see if this is true)

- [ ] #32 Dynmap is pretty buggy, things like changing the name from arda/Overworld crashes the server, will have to look into why 

- [x] ```/help``` page buttons are too small for the resourcepack font that clicking on them directly doesn't work

- [x] Overseer rank needs to have the ability to kick and temp ban

- [x] There is some bug with carpets #49

**Comment by dags-** [comment]
On the water thing:
The unusual levels of water could be placed by VoxelSniper/WorldEdit without it immediately updating and falling away, but there was never a means of physically placing blocks next to such water without triggering a blockupdate.

From what I was shown on Saturday, WorldEdit isn't able to place odd water levels like it used to (unless there's a nophysics setting for it that just needs to be enabled, or something).

However, with the `/nophysics` or `/np` command, users probably can now physically place blocks next to just about anything without triggering block updates.
`/nophysics` is a per-user toggle, so they just need to remember to use it before placing/breaking blocks around sensitive areas

**Comment by dags-** [comment]
- leaf decay - will test an updated method of preventing this
- missing slabs - extra rules required for slab metadatas in the worldfixer config (values 0 and 8 are valid)

**Comment by dags-** [comment]
### Resourcepack bugs
- my recommendation is to split 'fancy' models off into an overlay resourcepack - this'll improve performance for those who are happy with a more vanilla looking game, but offer the modded look for those that want it

- some blocks will need a custom model in the blockpacks - these should be relatively simple still and fit with the vanilla aesthetic, and again, fancier versions can be added to the overlay pack

**Comment by dags-** [comment]
Updated the worldfixer config to catch those slabs

**Comment by dags-** [comment]
Trimmed off the no-longer relevant issues and/or split off new Issues for further discussion/feedback

**Comment by Freshmilkymilk** [comment]
Haven't found anything wrong with world edit. It seems people aren't sure what id's to use for modblocks and that is the problem.

**Comment by Freshmilkymilk** [comment]
Updated with some new bugs.

**Comment by dags-** [comment]
Permissions for the Overseer one:
`bedrock.kick`
`minecraft.command.ban`

**Comment by dags-** [comment]
Can't do anything about the `/help` buttons on the plugin/server side of things.

Either:
- modify the font texture to line up the '<' and '>' characters properly
- just use the `/page next` and `/page previous` commands

**Comment by Freshmilkymilk** [comment]
Everything has been dealt with. Any further bugs for 1.8.9 will be posted as separate issues.
