### ISSUE TITLE
Per player time/weather

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#43]
(Sponge doesn't support per-player time yet)

Could have a client-side mod that blocks time/weather cycles unless toggled off by user.

Server-side, weather and time could be left on, so that users who are not blocking them with their mod can experience the same time and weather as each other.

The mod could also support:
- real-world local time
- setting and/or locking time to any value
- setting and/or locking weather to any value
- if possible, fake snowy conditions
- maybe reduce render distance in certain biomes to create a misty effect?

**Comment by Atlantispy** [comment]
Would it be possible to do some things by location rather than biome? I know the regions plugin could be a pain but selecting specifically marshes and the barrow downs to be misty for example would be nice.

**Comment by dags-** [comment]
Still need to give some thought to how mist might work. Don't particularly want there to have to be an extra server-side component to it (which regions would require)
Something better than just using biomes should be possible though
