### ISSUE TITLE
Links not always clickable

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#44]
Sponge doesn't yet automatically make URLs clickable.
LiteChat covers general chat messages. The following cases are not:
- [x] Private messages - [bedrock](https://github.com/ArdaCraft/Bedrock/commit/c9b0a78f1b3b75d6dae1d3a69738ea7eae5281c9)
- [ ] Dynmap web chat - not sure if this can be fixed

**Comment by Freshmilkymilk** [comment]
Dynmap links not working aren't much of a problem as the private messages are. Not too worried if those don't work, not even sure we'll keep dynmap chat on.

**Comment by dags-** [comment]
guess we could pass it off as a security feature since anyone can access dynamp and link harmful stuff ;]
