### ISSUE TITLE
Server status info on forums

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#48]
Could maybe use the 'top' customisable section (highlighted blue below) of the forums to display the minecraft server status & player count. Probably doesn't want to to be anything too flashy/imposing. Guessing it would need a bit of javascript magic. 

![screen](https://cloud.githubusercontent.com/assets/4276064/16885462/8e10af40-4ac6-11e6-9c20-125f96a28f27.png)

**Comment by dags-** [comment]
Testing something out: https://forums.ardacraft.me/

**Comment by Atlantispy** [comment]
So far what you've implemented works very well!

**Comment by HenrySlawniak** [comment]
minetools is really slow. I can write a faster collector to run on ardacraft.io
