### ISSUE TITLE
Bug with carpets

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#49]
Going off the below, there's a problem with carpets:
> [Do we know what's causing the issue with the carpets?](https://forums.ardacraft.me/t/the-big-update/183/49?u=dags)

No idea what kind of bug.
Maybe something to the Optifix mod which enables transparency on them

**Comment by Freshmilkymilk** [comment]
According to Fornad: "CTMs of yellow, brown, and light grey carpets all aren't working. Optifix still doesn't seem to be working fully, the moss carpet does though so it's weird. Think some ctms are broken in the 4.1 RP."

**Comment by dags-** [comment]
Oh, so a resource pack bug
