### ISSUE TITLE
Blockpack Update

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#50]
Need to update the blockpacks with new blocks. 
Wheellee has given a [spreadsheet](https://docs.google.com/document/d/1lAXthsif1z0G6bgyc_sraYjcKqshf3H4czmhgwCT6Ok/edit?usp=sharing) with all block types, names, etc.

I have all the files needed. Waiting on #22 to be finished to go through with updating the packs.

**Comment by Atlantispy** [comment]
Other blocks that could be added are ones that have models created by phe recently.

https://docs.google.com/spreadsheets/d/1F2kW6zM5jlGbJMTJbIQR3l0_bLuV0OOb-jsCD5JuSFo

List of completed ones here.

**Comment by Freshmilkymilk** [comment]
Kemce has done pretty much all the work for the latest update. The repo can be seen [here](https://github.com/ArdaCraft/BlocksPack-Lindon). Only thing that seems to not be working is the `Tall Lamp` I believe there is not block definition for it, so it is not showing up at all in the mod.
