### ISSUE TITLE
Leaf models

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#51]
To allow BetterFoliage to detect modblock leaves as leaf blocks, their models need to be updated from inheriting `block/cube_bottom_top` to `block/leaves` or `block/cube-all`.

Ref: [LeafRegistry](https://github.com/octarine-noise/BetterFoliage/blob/kotlin-1.8/src/main/kotlin/mods/betterfoliage/client/texture/LeafRegistry.kt#L51)

#### Example:
From this:
```
{
    "parent": "block/cube_bottom_top",
    "textures": {
        "bottom": "acblocks:blocks/leaves_apple_1",
        "top": "acblocks:blocks/leaves_apple_1",
        "side": "acblocks:blocks/leaves_apple_1"
    }
}
```

To this:
```
{
    "parent": "block/leaves",
    "textures": {
        "all": "acblocks:blocks/leaves_apple_1"
    }
}
```

----
Todo:
- [x] edit all current modded leaf-block models
- [ ] update block exporter to use this pattern too

**Comment by Freshmilkymilk** [comment]
Edited models as of a38c33c1c2bda3a7dc38f36282f8532e04f2d60a and 00558d83573f94a4b42fdf7d8668899fb6fb0421
