### ISSUE TITLE
Drop down menus on the map page.

### ISSUE THREAD

**Issue by Atlantispy** [ArdaCraft/IssueTracker#53]
It seems to be the case that when looking at the dynmap on the map page the drop down menus do not work

**Comment by HenrySlawniak** [comment]
I see what's wrong, we somehow put the map into the navbar. Working on this locally, also making the map page Better™

**Comment by HenrySlawniak** [comment]
Fixed in https://github.com/ArdaCraft/ardacraft.me/commit/2fb653fcc82d5627aac73041304cbec15aca16bb
