### ISSUE TITLE
Freebuild

### ISSUE THREAD

**Issue by Fornad** [ArdaCraft/IssueTracker#58]
Builders would like somewhere to work on their larger builds - a freebuild is needed

Organised into themed sections 1000x1000 wide with warps to the centre of each (Elves, Dwarves, Arnor, Orcs, Rohan, etc.)

Cross-server chat required (like with plots)

**Comment by dags-** [comment]
- Would be easy to have a plugin generate the world (could probably use a 1024x1024 grid to make the maths faster)
- Could possibly generate a sub-grid (32x32 block areas?) to help space projects out
- May want to include a world border/limit to avoid excessive generation
- No protections required. Prism would still be logging actions as it does on the main map
- Everything's running on the same server, so cross-world chat is already supported

**Comment by Fornad** [comment]
Kem came up with this method of sub-dividing it:

https://cdn.discordapp.com/attachments/207679119360655360/241201580915818499/freebuild_world.png

Something along those lines would be ideal, though it would require manual set-up. 

I think a world limit of 15kx15k would be fine to start with.

**Comment by Freshmilkymilk** [comment]
This has been implemented.
