### ISSUE TITLE
Launcher downloads MSI soundpack even if MAtmos not selected

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#59]
The MSI soundpack (about 75MB) gets downloaded whether MAtmos is selected for installation or not.
This adds a lot of necessary waiting time for users who don't use the MAtmos mod.

If possible (was with the old _old_ launcher), the resource should only be downloaded if MAtmos is selected for installation

**Comment by Freshmilkymilk** [comment]
Fixed with the latest packs.
