### ISSUE TITLE
Custom Launcher

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#60]
Have a custom Launcher. Currently we use [SKCraft's launcher](https://github.com/SKCraft/Launcher). It is pretty outdated, and doesn't provide all the things I'd want it to. We could create our own custom launcher from scratch.

What does the current launcher do well:

1. Fairly easy to use.
2. Updated by SKCraft, we don't need to do much to maintain it.
3. The back end is easy to use, and updates to the modpack are simple enough.

What would be nice to have in a new launcher:

1. Install the Java 8 JRE automatically.
2.  Modern UI.
3. Auto update Mods, RP's, and Blockpacks from github (or another source such as ardacraft.io).
4. Have an option to install the modpack to the default minecraft directory and allow people to use the default launcher. Implement from [ACInstaller](https://github.com/ArdaCraft/ACInstaller).

_I'll think of some more comments later and add it in._

**Comment by dags-** [comment]
I have a preference for using the Mojang launcher anyway, and it'd be a lot of work to even get something on level with SKLauncher, so this isn't something I'd like to work on personally.

There's a discussion [here](https://github.com/SKCraft/Launcher/issues/144) where SK mentions rewriting in something like Electron which would bring the more modern look.

**Comment by dags-** [comment]
> Auto update Mods, RP's, and Blockpacks from github (or another source such as ardacraft.io)

A bit like the RPUpdater mod I'm trialing, blockpacks and rp's could be updated via a mod, which could go in both the aclauncher and the installer modpacks.

As for mod updates, the launcher handles these quite nicely I think.
The installer requires users basically install a whole new modpack profile, which is not so nice, but I think acceptable-enough an experience given how infrequently the mods themselves change

**Comment by Freshmilkymilk** [comment]
>Modern UI.

SKCraft offers a 'fancy' version of the launcher that we could offer:

![](https://raw.githubusercontent.com/SKCraft/Launcher/master/readme/launcher_skinned.png)

This shouldn't be too much work to set up.

**Comment by Freshmilkymilk** [comment]
See https://github.com/ArdaCraft/ArdaCraftLauncher
