### ISSUE TITLE
Plugins for 1.10.2

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#62]
Update List
- [x] Badges*
- [x] DaFlightManager*
- [x] Dynmap (mod)
- [x] EnvProtect*
_Freebuild - not required_
- [x] Guests*
- [x] NoClip* (mod)
- [x] Plots*
- [ ] Prism
- [x] SchematicsBrush
- [x] ServicesCore*
- [x] Toolkit*
- [x] VoxelSniper
- [x] WorldEditSponge

----

Should probably consider Sponge plugin options for 1.10.2.

### Bedrock (Essentials-like plugin)
AC currently uses a custom build of prism/bedrock. The original repository for this plugin has not been updated to SpongeAPI 5+ so an alternative is required.

I can make some sort of script to transfer warps to the new system if needed.

### DPermissions (Permissions plugin)
There are a few new options for permission plugins available on Sponge now so we should consider switching. Would save me having to update it.

### LiteChat (Chat formatting plugin)
May not need a separate chat formatting plugin depending on the Bedrock/Permissions replacement(s)

I'll have a dig through the Sponge site and find some relevant _active_ plugin projects for api 5 and post links below. Feel free to do the same

**Comment by Freshmilkymilk** [comment]
> Essentials-like plugin

Looks like the most featured and updated plugin is [Nucleus](https://forums.spongepowered.org/t/0-18-0-nucleus-the-ultimate-essentials-plugin-mc-1-10-2-1-11/11792). - [Github](https://github.com/NucleusPowered/Nucleus)

> Permissions plugin

Could always go back to PEX. Although im not sure how completed and/or bloated this is. [PermissionsEx](https://forums.spongepowered.org/t/permissionsex-v2-0-api-5/6198) - [Github](https://github.com/PEXPlugins/PermissionsEx)

> Chat formatting

Not really a chat formatting plugin, but this is pretty neat: [Boop](https://github.com/pie-flavor/Boop)

## Going through what we have currently:

### Badges
Not sure.
### Daflight
[Updated for 1.10.2](https://github.com/DaFlight/DaFlight/releases/tag/1.10.2-5.0pre3)
### Dynmap
[Updated for 1.10.2](http://dynmap.us/builds/DynmapForge/)
### Guests
Not sure.
### NoClip
Would need to be updated.
### Plots
Would need to be updated.
### Prisim
Looks like there are no builds for SpongeAPI 5.
### SchematicBrush
Looks like there are no builds for SpongeAPI 5.
### VoxelSniper
[Updated for 1.10.2](http://ci.voxelmodpack.com/job/VoxelSniper/)
### EnvProtect
Not sure.
### Freebuild
Would need to be updated.
### Services
Would need to be updated.
### Toolkit
Not sure.
### WorldEdit
[Updated for 1.10.2](https://minecraft.curseforge.com/projects/worldedit/files)

## Some more plugins for 1.10.2

### [Project Worlds](https://forums.spongepowered.org/t/project-worlds-v0-11-4-world-manager/10170) (World Manager)
I'm not sure if we'd actually need a world manager, but if we do this is the plugin for it.
### [Project Portals](https://forums.spongepowered.org/t/project-portals-v0-13-4/10438)
If we're going to have a bungeecord setup between us and Conquest Reforged then being able to have portals in a spawn area would be good.
### [SpongyCord](https://forums.spongepowered.org/t/door-spongycord-a-simple-wrapper-api-for-bungee/13216)
API for bungeecord. If we use Project Portal you'd need this.
### [CommandSigns](https://forums.spongepowered.org/t/commandsigns-v1-3-1-api-6-0-0/9231/1)
Have signs that run commands. Would be good in the spawn area.

We'll also need to work out how we'll handle Bungeecord between Conquest Reforged.
This was talked about in #18 

> Some more links to maybe bookmark
 A more actively updated/developed fork of bungeecord:
https://github.com/WaterfallMC/Waterfall
A new(er) proxy server written in Java or Go, probably performs better - not sure if it supports proxy plugins, or Sponge for that matter:
https://github.com/LilyPad/JLilyPad
https://github.com/LilyPad/GoLilyPad

**Comment by dags-** [comment]
Ok, so I think we should aim for SpongeAPI 6.

There are breaking changes between API 5.0 and 5.1 (possibly between 5.1 and 6.0 too).
May as well update once to the latest API and avoid lots of incremental changes.

API 6 has SpongeForge builds for both mc 1.10.2 and 1.11.2
