### ISSUE TITLE
Mods for 1.10.2

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#63]
Update list:

Essential Mods -
- [x] Conquest Reforged
- [x] Optifine
- [x] Daflight
- [x] ACResource Updater
- [x] NoClip

Optional Mods -
- [x] Matmos
~~Journey Map~~
- [x] Voxel Map
- [x] Better Folliage
- [x] Tabby Chat
- [ ] Chunk Animator
~~Shaders Mod~~
- [x] Worldedit CUI
- [x] Presence Footsteps
- [x] Chat Bubbles

Suggest any other mods we'd like to have in the modpack below.

**Comment by Freshmilkymilk** [comment]
Tabby Chat is updated, but requires [liteloader](http://www.liteloader.com/) and [MnmUtils](https://minecraft.curseforge.com/projects/mnmutils/files): https://minecraft.curseforge.com/projects/tabbychat-2

MAtmos is updated: https://github.com/Sollace/MAtmos/releases

Presence Footsteps is updated: https://github.com/Sollace/Presence-Footsteps/releases

**Comment by Freshmilkymilk** [comment]
Added Chat Bubbles: https://minecraft.curseforge.com/projects/chat-bubbles

Shaders mod is also now apart of Optifine.

**Comment by dags-** [comment]
looks like chunk animator has skipped over 1.10, all others are up to date
