### ISSUE TITLE
Voxel Sniper

### ISSUE THREAD

**Issue by wheelleee** [ArdaCraft/IssueTracker#64]
It seems to be different in 1.10/8 compared to 1.7 (e.g. melt/lift/blend brushes work in completely different ways, the melt and blend not being nearly as strong and the lift not causing overhangs like it used to), and it's hard to change the 'settings' as well, the commands provided in the wiki to do that did not work. I'm not sure if this is a bug or not but since quite a few people have experienced this problem since the 1.8 update (and by proxy the 1.10 update), I decided to post this here.

**Comment by dags-** [comment]
not our plugin sorry
