### ISSUE TITLE
Backup Improvements

### ISSUE THREAD

**Issue by HenrySlawniak** [ArdaCraft/IssueTracker#65]
So checking in on backups, we seem to be hitting an issue

Ocassionally, we miss backing up region files due to the file being locked.

I also want to start pushing nightlies off of OVH's back to something like B2 or Glacier as a secondary, and then figuring out a tertiary.

I see two solutions to the file locks off the top of my head

1. Server process save the world out so it releases any locks, then run the backup script
2. Server dumps the world into another cold directory that we pull backups from periodically. (more frequently than the backup script)

Side note, nice job crashing the server last Friday
`[henry@mc ~]$ ls -hal /backup/*
/backup/cold:
total 20G
drwxrwxr-x 2 100 users    9 Nov 29 00:03 .
drwxr-xr-x 4 100 users    6 Jun 12  2016 ..
-rw-r--r-- 1 100 users 3.1G Nov 23 00:04 world.2017-11-22_00_00.tar.gz
-rw-r--r-- 1 100 users 867M Nov 24 00:01 world.2017-11-23_00_00.tar.gz
-rw-r--r-- 1 100 users 3.2G Nov 25 00:02 world.2017-11-24_00_00.tar.gz
-rw-r--r-- 1 100 users 3.2G Nov 26 00:02 world.2017-11-25_00_00.tar.gz
-rw-r--r-- 1 100 users 3.2G Nov 27 00:03 world.2017-11-26_00_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 00:03 world.2017-11-27_00_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 29 00:03 world.2017-11-28_00_00.tar.gz

/backup/world:
total 77G
drwxrwxr-x 2 100 users   27 Nov 29 01:00 .
drwxr-xr-x 4 100 users    6 Jun 12  2016 ..
-rw-r--r-- 1 100 users 3.3G Nov 28 01:17 world.2017-11-28_01_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 02:17 world.2017-11-28_02_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 03:16 world.2017-11-28_03_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 04:17 world.2017-11-28_04_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 05:16 world.2017-11-28_05_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 06:17 world.2017-11-28_06_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 07:16 world.2017-11-28_07_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 08:16 world.2017-11-28_08_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 09:16 world.2017-11-28_09_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 10:17 world.2017-11-28_10_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 11:15 world.2017-11-28_11_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 12:15 world.2017-11-28_12_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 13:16 world.2017-11-28_13_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 14:16 world.2017-11-28_14_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 15:16 world.2017-11-28_15_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 16:16 world.2017-11-28_16_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 17:16 world.2017-11-28_17_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 18:16 world.2017-11-28_18_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 19:17 world.2017-11-28_19_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 20:16 world.2017-11-28_20_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 21:16 world.2017-11-28_21_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 22:17 world.2017-11-28_22_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 28 23:19 world.2017-11-28_23_00.tar.gz
-rw-r--r-- 1 100 users 3.3G Nov 29 00:18 world.2017-11-29_00_00.tar.gz
-rw-r--r-- 1 100 users 672K Nov 29 01:01 world.2017-11-29_01_00.tar.gz
`

**Comment by HenrySlawniak** [comment]
@dags- and @Freshmilkymilk

**Comment by dags-** [comment]
The crash-report pointed to a failed file write during a player disconnect (still no idea why). Was it related to the backups then?


I was thinking the server should probably have periodic restarts as there seems to be a number of netty related leaks/bugs introduced by forge which they're not fixing in 1.10.2. Maybe that could be tied into the backup script? Guess it might take a while between restarts if there's a full copy going on though

**Comment by HenrySlawniak** [comment]
Doubt the backups were tied to the crash, just a funny ripple I saw.

We may be able to solve all of this through some RCON scripting, just dumping a `save-all`, which should let go of the file locks, then backing up. Need to see what kind of a hitch it causes in-game though.

**Comment by Freshmilkymilk** [comment]
Fixing up backups seems like a good idea.

Input I have is pricing and ease of use.

Currently OVH backups cost $2.50 a month for 100gb's of storage. Anything close or less than that would be perfect. The forums are currently backed up on Amazon s3, so using glacier might be a good option to go with that.

**Comment by HenrySlawniak** [comment]
I was looking at B2 since it would probably be under a dollar a year for us

https://www.backblaze.com/b2/cloud-storage-pricing.html
