### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#67]
Currently our guides page is outdated and not very useful.

having a dedicated wiki @ wiki.ardacraft.me or ardacraft.me/wiki would be idea.

i know dags has shown off a little wiki site he's been working on. Would be good to either fully get that working, or find something that would work.

Things the wiki needs - 
Ease of use (non technical people should be able to use it)
Logins (allow certain individuals to edit wiki)

**Comment by dags-** [comment]
I wasn't so much working on a wiki, I'd just installed a wiki software on a server to test it out. Don't even remember which one it was

Anyways, I think this could possibly be rolled into the dev website issue.

Like a general 'docs' site which would host guides, mod/plugin documentation, showcase pages etc. 
And sure, fronted by some pretty landing page like the .me page is to the forums

**Comment by Fornad95** [comment]
Happy to write any articles for this myself.

**Comment by Freshmilkymilk** [comment]
Built here: https://github.com/ArdaCraft/Wiki
