### ISSUE TITLE
Console clean up

### ISSUE THREAD

**Issue by Freshmilkymilk** [ArdaCraft/IssueTracker#72]
The current console output is cluttered with errors:
Full output: [link](https://gist.github.com/Freshmilkymilk/b25b63a5f1f5a708273ee2bd8e8f8eb1)
I would like to bring this down so the startup is cleaned up if we ever need to troubleshoot.

Specific Errors:
`[net.minecraft.advancements.AdvancementManager]: Parsing error loading built-in advancement minecraft`
This error happens for:
- wooden_shovel
- wooden_pickaxe
- wooden_hoe
- wooden_axe
- trapdoor
- cobblestone_wall
- wooden_sword
- stone_brick_stairs

`DynmapBlockScan`
This throws a load of errors not being able to open blockstates, open models, generating elements, or adding patches

`Dynmap`
Throws bad custom colors for various block ID's

Options:
1. Not sure what's causing the first issue, I'm assuming it's conquest reforged editing recipes?
2.  I'm using [DynmapBlockScan](https://github.com/webbukkit/DynmapBlockScan) as it has the most "accurate textures" We've previously used dags' [DynmapBlockScrapper](https://github.com/dags-/BlockScraper) which works better in my opinion but at it's current state it doesn't use the right textures for leaves, and some block models are wrong. I can update dags if he needs specific issues to help fix his plugin.
3. Is this an issue with the way custom colors are defined via the resourcepack?

**Comment by dags-** [comment]
1. I think I've seen the spongeforge server produce these errors without any mods installed, so I'd assume it's a forge or sponge thing

2. It's mostly complaining about the hundreds of `conquest:none` blockstates (the bright green placeholders) because they don't have a proper models. Will go away in 1.13 since they won't exist any more
