### ISSUE TITLE
Better Foliage for Mod-block Leaves

### ISSUE THREAD

**Issue by dags-** [ArdaCraft/IssueTracker#9]
If the mod supports it, configure to add better leaves to mod-block leaves

**Comment by Freshmilkymilk** [comment]
Using better foliage 1.8.x-2.0.12

- Some modblock leaves turn invisible.

- Modblock leaves don't have any of the extra bits

- Extra grass on Mycelium is pretty buggy

[Here's](https://imgur.com/a/KQRgV) some screenshots

**Comment by dags-** [comment]
On adding support for modblock leaves:
> Better Foliage has a configurable way to identify interesting blocks (grass, leaves, etc.) you can find in the configuration GUI. It works by matching the Java class name of the block againt a blacklist/whitelist pair. This is how support for modded blocks is added.

> However, you will rarely need to touch this at all. I will always add new blocks to the default lists as I become aware of them, and the change will be available to you from the next version on.

Reference (bottom of page): http://minecraft.curseforge.com/projects/better-foliage/pages/features

---

If someone who uses the mod would like to configure this, the configuration files could be added to the launcher and shared with others.

**Comment by dags-** [comment]
As there are issues with vanilla blocks, it would suggest that this is not a compatibility issue between our custom blocks mod and better foliage, but due to bugs within better foliage itself - we can't do anything about that.

**Comment by Freshmilkymilk** [comment]
Here is the config of the mod:
https://gist.github.com/Freshmilkymilk/22e898409bd46b938cfa140f1e0f266d

**Comment by dags-** [comment]
Made any progress with the leaves Fresh?
Looks like you can add `me.dags.creativeblock.block.CBLeaves` under the [`S:leavesWhitelist`](https://gist.github.com/Freshmilkymilk/22e898409bd46b938cfa140f1e0f266d#file-better-foliage-config-L44) section of the config

**Comment by Freshmilkymilk** [comment]
Leaves have been fixed with the updates done to the BlockPacks. An update will be pushed in the near future to add Better Foliage back in.
